import numpy as np
import matplotlib.pyplot as plt
f = float(input("enter the frequency:"))
t= np.linspace(0,10,500)
n=np.linspace(0,10,100)
cosine = np.cos(2*np.pi*f*t)
cosine_n = np.cos(2*np.pi*f*n)
fig,a=plt.subplots(2,1)
a[0].plot(t,cosine)
a[0].set_xlabel("time")
a[0].set_ylabel("amplitude")
a[1].stem(n,cosine_n)
a[1].set_xlabel("time")
a[1].set_ylabel("amplitude")
plt.show()